name: Check for team-provider-info.json changes

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - qa

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for modifications to team-provider-info.json
        run: |
          if git diff --name-only HEAD^ HEAD | grep 'amplify/team-provider-info.json'; then
            echo "team-provider-info.json has been modified."
            echo "::set-output name=file-modified::true"
          else
            echo "team-provider-info.json has NOT been modified."
            echo "::set-output name=file-modified::false"
          fi

      - name: Fail if team-provider-info.json was modified (can skip this if allowed sometimes)
        run: |
          if [ "${{ steps.check-files.outputs.file-modified }}" == "true" ]; then
            echo "Error: Modifications to team-provider-info.json are not allowed."
            exit 1
          fi
