name: Check for team-provider-info.json changes

on:
  pull_request:
    branches:
      - qa  # Specify the base branch for PRs

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to access all branches

      - name: Check for modifications to team-provider-info.json
        run: |
          # Pull request branch
          echo "Pull request branch is: ${{ github.head_ref }}"

          # Ensure both branches are available
          git fetch origin qa
          git fetch origin ${{ github.head_ref }}  # Fetch the PR branch

          # Check if the team-provider-info.json has been modified
          if git diff --name-only origin/qa...${{ github.head_ref }} | grep 'amplify/team-provider-info.json'; then
            echo "team-provider-info.json has been modified."
            echo "file-modified=true" >> $GITHUB_ENV
          else
            echo "team-provider-info.json has NOT been modified."
            echo "file-modified=false" >> $GITHUB_ENV
          fi

      - name: Fail if team-provider-info.json was modified
        if: env.file-modified == 'true'
        run: |
          echo "Error: Modifications to team-provider-info.json are not allowed."
          exit 1

